POST  http://localhost:7001/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic MTIzNDU2OjEyMzQ1Ng==

username=admin
&password=a0bc807b86bce3e63ad621eec41c3eb5
&grant_type=password
&scope=web

### 
get http://localhost:7001/oauth/test
Content-Type: application/json
Authorization: Bearer 995ceee5063d376c66b221362ab3b3a4861b4c2f


###
POST  http://localhost:7001/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic MTIzNDU2OjEyMzQ1Ng==

refresh_token=e5b8ee1656e1d7349f4cd4e0d68a5b85c8850525
&grant_type=refresh_token